name: "Build"
on: [push, workflow_dispatch]
jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['bats-ansible-debian:latest', 'bats-ansible-debian:buster']
        include:
          - image: bats-ansible-debian:latest
            os: debian
            tag: latest
          - image: bats-ansible-debian:buster
            os: debian
            tag: buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.os }}/${{ matrix.tag }}
          file: ./${{ matrix.os }}/${{ matrix.tag }}/Dockerfile
          push: true
          tags: alzadude/${{ matrix.image }}
